# Introduction

This book describes long-term trends in population density for Yellowstone cutthroat trout (YCT) in the upper Snake River watershed, Wyoming, USA. All YCT data were provided by the Wyoming Game and Fish Department. Our goals are to describe long-term trends in YCT population density using multiple datasets (mark-recapture population estimates, redd counts, and spawning population enumeration using a weir) and evaluate variation in trends among populations. 

*This information is preliminary or provisional and is subject to revision. It is being provided to meet the need for timely best science. The information has not received final approval by the U.S. Geological Survey (USGS) and is provided on the condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from the authorized or unauthorized use of the information.*

Project team: Jeff Baldock and Annika Walters

------------------------------------------------------------------------

<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne">

Session Information

</button>

:::: {#collapseOne .accordion-collapse .collapse}
<div>

```{r}
sessionInfo()
```

</div>
::::
